/* Gerado por scripts/gerar-assets-vitrine.ts: não editar à mão.
   O catálogo vem de prisma/catalogo-auvp.ts, a mesma fonte do seed. */
const CATEGORIAS = [
  "Personalizado AUVP",
  "Bebida",
  "Bebês e Crianças",
  "Beleza e Bem estar",
  "Livro"
]
const PRODUTOS = [
  {
    "slug": "agenda-e-caneta-auvp",
    "nome": "Agenda e Caneta AUVP",
    "categoria": "Personalizado AUVP",
    "valor": null,
    "origem": "estoque_interno",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "bone-capitalismo",
    "nome": "Boné Capitalismo",
    "categoria": "Personalizado AUVP",
    "valor": 35,
    "origem": "estoque_interno",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "caneca-auvp",
    "nome": "Caneca AUVP",
    "categoria": "Personalizado AUVP",
    "valor": null,
    "origem": "estoque_interno",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "caneta-e-moleskine-auvp",
    "nome": "Caneta e Moleskine AUVP",
    "categoria": "Personalizado AUVP",
    "valor": null,
    "origem": "estoque_interno",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "carteira-auvp",
    "nome": "Carteira AUVP",
    "categoria": "Personalizado AUVP",
    "valor": 35,
    "origem": "estoque_interno",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "garrafa-auvp",
    "nome": "Garrafa AUVP",
    "categoria": "Personalizado AUVP",
    "valor": null,
    "origem": "estoque_interno",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-canga-auvp",
    "nome": "Kit Canga AUVP",
    "categoria": "Personalizado AUVP",
    "valor": null,
    "origem": "estoque_interno",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-mochila-auvp",
    "nome": "Kit Mochila AUVP",
    "categoria": "Personalizado AUVP",
    "valor": 135,
    "origem": "estoque_interno",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "meia-auvp",
    "nome": "Meia AUVP",
    "categoria": "Personalizado AUVP",
    "valor": 25,
    "origem": "estoque_interno",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-churrasco-auvp-com-faca",
    "nome": "Kit Churrasco AUVP com faca",
    "categoria": "Personalizado AUVP",
    "valor": 330,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": "Pedido direto ao fornecedor",
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-churrasco-auvp-com-garra-e-acessorios",
    "nome": "Kit Churrasco AUVP com Garra e Acessórios",
    "categoria": "Personalizado AUVP",
    "valor": 380,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": "Pedido direto ao fornecedor",
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "cadeira-de-balanco-baby-menina",
    "nome": "Cadeira de balanço Baby - Menina",
    "categoria": "Bebês e Crianças",
    "valor": 199,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/cadeira-de-descanso-musical-funtime-new-maxi-baby-color-rosa/p/MLB35340528",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "cadeira-de-balanco-baby-menino",
    "nome": "Cadeira de balanço Baby - Menino",
    "categoria": "Bebês e Crianças",
    "valor": 199,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/cadeira-de-descanso-e-balanco-funtime-18kgs-coruja-maxi-baby/p/MLB28318987",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "cadeira-de-balanco-baby-unissex",
    "nome": "Cadeira de balanço Baby - Unissex",
    "categoria": "Bebês e Crianças",
    "valor": 199,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/cadeira-de-descanso-e-balanco-bebe-musical-funtime-maxi-baby-baxter-esquilo/p/MLB38626962",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "tapete-musical-baby-menina",
    "nome": "Tapete Musical Baby - Menina",
    "categoria": "Bebês e Crianças",
    "valor": 110,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/tapete-de-atividades-para-bebe-com-piano-musical-removivel/up/MLBU4256984980",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "tapete-musical-baby-menino",
    "nome": "Tapete Musical Baby - Menino",
    "categoria": "Bebês e Crianças",
    "valor": 110,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/tapete-de-atividades-para-bebe-com-piano-musical-removivel/up/MLBU4236577373",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-presente-granado",
    "nome": "Kit Presente Granado",
    "categoria": "Beleza e Bem estar",
    "valor": 150,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/kit-presente-spa-granado-castanha-do-brasil-skincare-caixa/p/MLB2105895362",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-presente-loccitane-roma",
    "nome": "Kit Presente Loccitane Romã",
    "categoria": "Beleza e Bem estar",
    "valor": 290,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/kit-presente-roma-loccitane-spraygeleiaesfoliante--sacola/up/MLBU4368898303",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "livro-a-arte-de-gastar-dinheiro",
    "nome": "Livro - A arte de gastar dinheiro",
    "categoria": "Livro",
    "valor": 35,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/a-arte-de-gastar-dinheiro-escolhas-simples-para-uma-vida-equilibrada-do-mesmo-autor-de-a-psicologia-financeira-housel-morgan-harper-business-capa-mole/p/MLB53908652",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "livro-a-psicologia-financeira",
    "nome": "Livro - A Psicologia Financeira",
    "categoria": "Livro",
    "valor": 35,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/a-psicologia-financeira-housel-morgan-harper-business-capa-mole/p/MLB19320442",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "caixa-mdf-para-vinho-com-acessorios-escolha-o-vinho",
    "nome": "Caixa MDF para vinho com Acessórios - Escolha o vinho",
    "categoria": "Bebida",
    "valor": null,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": "Pedido direto ao fornecedor",
    "exigeAcompanhamento": "vinho",
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-abridor-de-garrafas-cerveja-artesanal",
    "nome": "Kit Abridor de Garrafas + Cerveja Artesanal",
    "categoria": "Bebida",
    "valor": 170,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://colombina-express.lojaintegrada.com.br/cerveja-colombina-ipa-600ml",
    "notaDeCompra": "Pedido direto ao fornecedor (abridor)",
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-aperol",
    "nome": "Kit Aperol",
    "categoria": "Bebida",
    "valor": 315,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/kit-presente-aperol-spritz-espumante-chandon-brut-taca-vidro/p/MLB2097820350",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-cafe-constantino",
    "nome": "Kit Café Constantino",
    "categoria": "Bebida",
    "valor": 190,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.mercadolivre.com.br/kit-cafe-500g-moido-presente-barista-singelo-constantino/up/MLBU4355517358",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-cafe-orfeu-com-prensa-francesa",
    "nome": "Kit Café Orfeu com Prensa Francesa",
    "categoria": "Bebida",
    "valor": 210,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.robertadecoracoes.com.br/215c2c/cesta-presente-cafe-premium-com-acessorios-o-presente-ideal",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-caneca-de-chopp-cerveja-artesanal",
    "nome": "Kit Caneca de Chopp + Cerveja Artesanal",
    "categoria": "Bebida",
    "valor": 110,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://colombina-express.lojaintegrada.com.br/kit-colombina-cerrado-01",
    "notaDeCompra": "Pedido direto ao fornecedor (caneca)",
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-queijos-com-vinho-escolha-o-vinho",
    "nome": "Kit Queijos com Vinho - Escolha o vinho",
    "categoria": "Bebida",
    "valor": 165,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": "Pedido direto ao fornecedor",
    "exigeAcompanhamento": "vinho",
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "kit-vinho-com-abridor-eletrico-e-petisqueira-escolha-o-vinho",
    "nome": "Kit Vinho com Abridor Elétrico e Petisqueira - Escolha o vinho",
    "categoria": "Bebida",
    "valor": 215,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": null,
    "notaDeCompra": "Pedido direto ao fornecedor",
    "exigeAcompanhamento": "vinho",
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "vinho-alma-negra",
    "nome": "Vinho Alma Negra",
    "categoria": "Bebida",
    "valor": 200,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/alma-negra-m-blend-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-angelica-zapata-cabernet-franc",
    "nome": "Vinho Angelica Zapata Cabernet Franc",
    "categoria": "Bebida",
    "valor": 350,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/angelica-zapata-cabernet-franc-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-carnivor-zinfandel",
    "nome": "Vinho Carnivor Zinfandel",
    "categoria": "Bebida",
    "valor": 150,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/vinho-carnivor-zinfandel-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-dv-catena-cabernet-malbec",
    "nome": "Vinho DV Catena Cabernet Malbec",
    "categoria": "Bebida",
    "valor": 250,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/vinho-dv-catena-cabernet-malbec-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-el-enemigo",
    "nome": "Vinho El Enemigo",
    "categoria": "Bebida",
    "valor": 300,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/el-enemigo-cabernet-franc-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-marques-de-tomares",
    "nome": "Vinho Marques de Tomares",
    "categoria": "Bebida",
    "valor": 120,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/marques-de-tomares-crianza-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-pintas-character-tinto",
    "nome": "Vinho Pintas Character Tinto",
    "categoria": "Bebida",
    "valor": 350,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/pintas-character-tinto-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-poeira-douro-37-barricas",
    "nome": "Vinho Poeira Douro 37 Barricas",
    "categoria": "Bebida",
    "valor": 450,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/vinho-poeira-douro-37-barricas-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-poeme-gran-reserva-cabernet-syrah",
    "nome": "Vinho Poeme Gran Reserva Cabernet Syrah",
    "categoria": "Bebida",
    "valor": 120,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/vinho-poeme-gran-reserva-cabernet-syrah-750ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-premier-rendez-vous-merlot-cabernet",
    "nome": "Vinho Premier Rendez Vous Merlot Cabernet",
    "categoria": "Bebida",
    "valor": 120,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/vinho-premier-rendez-vous-merlot-cabernet-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-ruben-e-flora-cabernet-e-carmenere",
    "nome": "Vinho Ruben E Flora Cabernet E Carmenere",
    "categoria": "Bebida",
    "valor": 120,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/vinho-ruben-e-flora-cabernet-e-carmenere-750ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-silk-e-spice",
    "nome": "Vinho Silk & Spice",
    "categoria": "Bebida",
    "valor": 100,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/silk-e-spice-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-soprasasso-amarone-della-valpolicella",
    "nome": "Vinho Soprasasso Amarone Della Valpolicella",
    "categoria": "Bebida",
    "valor": 400,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/vinho/vinho-soprasasso-amarone-della-valpolicella-750ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "vinho-telmo-e-ruth-cabernet-e-merlot",
    "nome": "Vinho Telmo E Ruth Cabernet E Merlot",
    "categoria": "Bebida",
    "valor": 120,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/chile/vinho-telmo-e-ruth-cabernet-e-merlot-750ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": "vinho",
    "semFoto": false
  },
  {
    "slug": "whisky-bulleit-bourbon-750-ml",
    "nome": "Whisky Bulleit Bourbon 750 ml",
    "categoria": "Bebida",
    "valor": 250,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/whisky/bulleit-bourbon-750-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "whisky-eagle-rare-10-anos-750-ml-bourbon",
    "nome": "Whisky Eagle Rare 10 anos 750 ml - Bourbon",
    "categoria": "Bebida",
    "valor": 250,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/whisky/whiskey-eagle-rare-10-anos-750-ml-bourbon/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "whisky-gentleman-jack-1000-ml",
    "nome": "Whisky Gentleman Jack 1000 ml",
    "categoria": "Bebida",
    "valor": 250,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/natale/kit-gentleman-jack-1000ml-copo-vidro/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "whisky-singleton-12-anos-dufftown-750-ml",
    "nome": "Whisky Singleton 12 Anos Dufftown 750 ml",
    "categoria": "Bebida",
    "valor": 200,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/whisky/singleton-12-anos-of-glen-ord-700-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "whisky-toki-suntory-700ml",
    "nome": "Whisky Toki Suntory 700ml",
    "categoria": "Bebida",
    "valor": 200,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/whisky/whisky-suntory-toki-700ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "whisky-wild-turkey-rye-700-ml",
    "nome": "Whisky Wild Turkey Rye 700 ml",
    "categoria": "Bebida",
    "valor": 300,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/whisky/wild-turkey-rye-700-ml/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  },
  {
    "slug": "whisky-woodford-reserve-bourbon",
    "nome": "Whisky Woodford Reserve Bourbon",
    "categoria": "Bebida",
    "valor": 250,
    "origem": "mediante_pedido",
    "ativo": true,
    "urlCompra": "https://www.casadabebida.com.br/blue-week/kit-whisky-woodford-reserve-700ml-copo/",
    "notaDeCompra": null,
    "exigeAcompanhamento": null,
    "serveComoAcompanhamento": null,
    "semFoto": false
  }
]
